# Disable sending stats
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactNativeDji' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for ReactNativeDji
  pod 'DJI-SDK-iOS', '~> 4.9'

end
